### ISSUE TITLE
A23 - Bannière publicitaire

### ISSUE THREAD

**Issue by QcSiM008** [gti525/h18-vente1#23]
En tant que site de vente, je dois pouvoir afficher une bannière publicitaire provenant du service de publicité développé par l'équipe d'analytique et de publicité.

Exigences techniques:
Communiquer avec l'équipe Analytique et Publicité, ou consulter leur documentation publique

**Comment by arie1302** [comment]
Ceci est déjà fait afin de pouvoir rassurer le groupe de analytique.
