### ISSUE TITLE
A28 - Modif/Supp salle (API)

### ISSUE THREAD

**Issue by QcSiM008** [gti525/h18-vente1#28]
En tant que système je dois permettre d'effectuer des modifications et suppressions de salle via l'API uniquement à l'administrateur de salle associé, ou à un administrateur du site Web de vente.

**Comment by arie1302** [comment]
A28 signifie si il y a 2 administrateurs externes différent qu'un ne peut deleter des spectacles d'un autre

Bref un admin A ne peut pas supprimer la ou les salles possédées par l'admin B (Voir Éric pour plus de détails si jamais c'est pas assez clair)


De plus, il y a aussi l'ajout dune salle.
