### ISSUE TITLE
A36 - En tant que développeur je dois concevoir les prototype statiques HTML / CSS

### ISSUE THREAD

**Issue by gregoirefra** [gti525/h18-vente1#35]
Fichier .zip contenant le prototype statique de l’application. Les fichiers HTML de l’application doivent pouvoir être ouverts dans un navigateur Web. Ce prototype a pour but de présenter la séquence de navigation dans le site et de donner un aperçu de l’expérience utilisateur à prévoir lorsque la portion dynamique du site sera codée.

**Comment by arie1302** [comment]
**- Page Accueil changement et doit contenir :** 
         - [ ] Strip toutes la Barre Menu : va contenir ( Onglet Quick Seach , Voir tous les spectacles et Le panier "Mes spectacles")
         - [ ] Ajouter le logo
         - [ ] Carrousel : Va afficher les top 3 vendu en fonction du nombres de billets restants à vendre
         - [ ] Change En vedette pour  Recommandé pour vous (Spectacle) 
         - [ ] Modal pour le bouton info sur un spectacle : va contenir infos du spectacle & Quantité de billets & bouton Ajouter au panier 
         - [ ] Quand on click sur le Panier "Mes spectacles" : Affichage de la liste des achats & les quantités + Doit avoir possibilité de changer les quantités et de le retirer du panier + Avoir le bouton Passer la commande
         - [ ] Sur les spectacles, ON ENLÈVE les boutons Comparer et les favoris vont seulement s'afficher en fonction si il est connecté avec le compte réseau social (À voir car ce n'est pas un requis)

**-Page Se connecter** 
Attention!!! -> Elle doit afficher avant la page Passer à la commande si l'utilisateur ne s'est pas connecté ou il désire acheter en tant qu'invité. 
         - [ ] Avoir la section connexion Réseau Social
         - [ ] Avoir la section connexion En tant qu'invité -> Ce qui mène à la page passer à la commande

**-Page Passer à la commande doit contenir :**
         - [ ] Garder la bannière et le logo
         - [ ] Affichage du temps restant avant de perdre les billets 
         - [ ] Affichage du processus et où il est rendu dans le processus du Checkout + Processus est Informations clients > Informations paiements > Confirmation de la commande

**-Page du reçu de commande doit contenir :**
         - [ ] Code de confirmation (# du billet )
         - [ ] Photo du spectacle
         - [ ] Nom du spectacle
         - [ ] Salle du spectacle
         - [ ] Date du spectacle
         - [ ] Permet l'impression des billets ou PDF

**-Page admin (À voir cela entre dans le prototype statique ) Voir le chargé demain** 

**-Page Spectacle doit contenir :**
Attention-Bouton Voir tous les spectacles et Résultat du quick search (page accueil) arrive  à la même page avec différent filtre. 
         - [ ] Affichage des spectacles en mosaïque
         - [ ] Une barre de filtre pour faire une recherche approfondi 
         - [ ] Garder le même Header avec le logo qui permet de revenir à la page d'accueil
         - [ ] P-t avec un fils d'Ariane pour montrer à l'utilisateur où il est rendu dans la navigation
